version: "2.4"
services:
  bookstore-server:
    container_name: "bookstore-server"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - TZ=Europe/Berlin
      - JAVA_OPTS=-Xmx4G
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bookstoredemo
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      # amount of randomly generated data, supported values: minimal, small, medium, large, humongous
      - BOOKSTOREDEMO_INITIALDATAAMOUNT=medium
    mem_reservation: 4g
    mem_limit: 4g
  db:
    container_name: "bookstore-db"
    image: "postgres:13.4"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "bookstoredemo"
volumes:
  postgres_data:
